### ISSUE TITLE
Recommend not using README file to document all functions

### ISSUE THREAD

**Issue by schuemie** [OHDSI/ROhdsiWebApi#10]
Please adopt Methods Library practices (so this package can be included in the Methods Library), including

- Adding travis.yml and deploy.sh for continuous integration.
- Adding unit test to a tests subfolder if feasible.
- Follow the prescribed README sections
- Use pkgdown to generate a package website

A good example is the [ParallelLogger package](https://github.com/OHDSI/ParallelLogger], with [accompanying website](https://ohdsi.github.io/ParallelLogger/).

**Comment by alondhe** [comment]
Thanks @schuemie , will work on this in a new branch here, and for Achilles as well.
