### ISSUE TITLE
is there a more efficient way to return all results from incidence rate id

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/ROhdsiWebApi#102]
```
 url <- sprintf("%1s/ir/%2s/report/%3s?targetId=%4s&outcomeId=%5s", 
                 baseUrl, 
                 incidenceRateId, 
                 sourceKey, 
                 targetCohortId, 
                 outcomeCohortId
  )
```

Current approach appears to be do a seperate call for every combination of targetId, outcomeId, sourceKey

Can we create a new endpoint (or do we have an alternative) that is able to get all the results, for all target/comparator id combination AND sourceKeys?

@anthonysena @chrisknoll

**Comment by anthonysena** [comment]
@gowthamrao - I haven't looked deeply into the package but you can obtain a summary for a given IR ID using this WebAPI endpoint `WebAPI/ir/<id>/info` and then for each source, get a summary via: `WebAPI/ir/<id>/info/<sourceKey>/`. Apologies if you've already implemented this but for the URL above, that's is what is currently offered from WebAPI to facilitate the operations required by ATLAS.

**Comment by gowthamrao** [comment]
@anthonysena  thank you.
