### ISSUE TITLE
RJSONIO::toJSON loss of precision

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/ROhdsiWebApi#152]
An example of this: when serializing a cohort definition, a concept set included in the definition had this concept and concept_id:

siltuximab
concept_id == 44818461

The default settings for RJSONIO::toJSON() change this formatting of this concept in JSON to use scientific notiation thus resulting in the value:

4.481846e+07

When re-hydrating this definition that contains scientific notation, the concept_id is then incorrectly specified as `44818460` instead which is a different drug. 

The solution (which was found in the code base) is to use the `digits` formatting extension:

RJSONIO::toJSON(data, **digits = 23**)

**Comment by gowthamrao** [comment]
@anthonysena do you think it would be useful to show a working example? If true, this is a major high priority issue and will require 'deep cleansing'

**Comment by anthonysena** [comment]
Here is one:

``` r
foo <- list(expression = list(ConceptSets = list(list(expression = list(items = list(list(concept = list(CONCEPT_ID = 44818461))))))))
foo$expression$ConceptSets[[1]]$expression$items[[1]]$concept$CONCEPT_ID
#> [1] 44818461
RJSONIO::toJSON(foo, pretty = TRUE)
#> [1] "{\n\t\"expression\" : {\n\t\t\"ConceptSets\" : [\n\t\t\t{\n\t\t\t\t\"expression\" : {\n\t\t\t\t\t\"items\" : [\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\"concept\" : {\n\t\t\t\t\t\t\t\t\"CONCEPT_ID\" : 4.481846e+07\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t\t}\n\t\t]\n\t}\n}"
RJSONIO::toJSON(foo, digits = 23, pretty = TRUE)
#> [1] "{\n\t\"expression\" : {\n\t\t\"ConceptSets\" : [\n\t\t\t{\n\t\t\t\t\"expression\" : {\n\t\t\t\t\t\"items\" : [\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\"concept\" : {\n\t\t\t\t\t\t\t\t\"CONCEPT_ID\" : 44818461\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t\t}\n\t\t]\n\t}\n}"
```

<sup>Created on 2020-08-13 by the reprex package (v0.3.0)</sup>

I'm thinking it is probably best to make a single utility function called "toJSON" that wraps RJSONIO with these settings and use this in the code base. I'll put together a PR to address this one shortly.

**Comment by anthonysena** [comment]
FYI - This only seems to happen if the ID is >= 10,000,000.

**Comment by gowthamrao** [comment]
Thanks @anthonysena 

Continuing your foo example above

`a <- RJSONIO::toJSON(foo, pretty = TRUE)`

Here CONCEPT_ID = 4.481846e+07 - in scientific notation

Reconverting to list from JSON

> b <- RJSONIO::fromJSON(a)

Here CONCEPT_ID =  44818460 


This is also discussed here https://rstudio-pubs-static.s3.amazonaws.com/31702_9c22e3d1a0c44968a4a1f9656f1800ab.html

![image](https://user-images.githubusercontent.com/13936600/90234275-6d5cb000-dded-11ea-8b69-9dd99e6a1294.png)

**Comment by gowthamrao** [comment]
Thank you for detailing this bug and providing a fix for it
