### ISSUE TITLE
Add a vignette on inserting cohorts into a package?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/ROhdsiWebApi#157]
A common task is to insert the JSON and SQL into a package, so that package can instantiate these cohorts at any site. Currently there is no documentation that walks you through all the steps of how to do this. Could a vignette be added to ROhdsiWebApi?

**Comment by gowthamrao** [comment]
https://github.com/OHDSI/ROhdsiWebApi/blob/master/vignettes/InsertCohortDefinitionsIntoPackage.Rmd
