### ISSUE TITLE
getCohortInclusionRulesAndCounts - get both events and persons

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/ROhdsiWebApi#16]
Atlas has two tabs in cohort generation report
- By Events
- By Persons

It would be nice to have data from both of them returned by one function. This would help mirror the output in Atlas.

**Available in current version: from 'By Events' tab in Atlas**
$countSatisfying  -- 'N' (By Events)
$percentSatisfying -- %satisfied (By Events)
$percentExcluded -- %to-gain (By Events)
`
**Not Available in current version: from 'By Person' tab in Atlas**
'N' (By Persons)
'% remain' (By Persons)
'% difference' (By Persons)

There may be a way to calculate 'By Person' from current output, but i am not clear how to. It would be nice to get that pre-computed by the function.

**Comment by anthonysena** [comment]
Another potential option here is to make the "mode" QueryString parameter of WebAPI an optional parameter to the `getCohortInclusionRulesAndCounts` function call. It can default to mode = 0 (By Event) and allow an override to mode = 1 (By Persons):

https://github.com/OHDSI/ROhdsiWebApi/blob/master/R/CohortDefinition.R#L516

**Comment by gowthamrao** [comment]
Closed thru https://github.com/OHDSI/ROhdsiWebApi/pull/68
