### ISSUE TITLE
Error in getConceptSetsFromCohortDefinition()

### ISSUE THREAD

**Issue by tomseinen** [OHDSI/ROhdsiWebApi#167]
I get an error when running the getConceptSetsFromCohortDefinition() function.

Example:
```R
baseUrl<-"http://atlas-covid19.ohdsi.org/WebAPI"
cohortDef<-ROhdsiWebApi::getCohortDefinition(baseUrl = baseUrl,cohortId = 1147)
conceptSets<-ROhdsiWebApi::getConceptSetsFromCohortDefinition(CohortDef)
```
The error I get is:
`Error: Internal error in 'vec_assign()': 'value' should have been recycled to fit 'x'.`
backtrace:
```
Backtrace:
  1. ROhdsiWebApi::getConceptSetsFromCohortDefinition(CohortDef)
  2. expression$ConceptSets
  9. purrr::map_df(., .f = purrr::flatten)
 10. dplyr::bind_rows(res, .id = .id)
 11. vctrs::vec_rbind(!!!dots, .names_to = .id)
```

Do others also get this error? Or is it just me?
I updated the dependencies to the latest version.

Thank you!

**Comment by gowthamrao** [comment]
Also related to https://github.com/OHDSI/ROhdsiWebApi/issues/169

https://github.com/OHDSI/ROhdsiWebApi/commit/44531a8ac5ebca4f2f9cf559cb225b199aa0a53a

this function is more appropriate for a package like ConceptSetDiagnostics or CapR
