### ISSUE TITLE
getConceptSetsExpressionFromCohort 

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/ROhdsiWebApi#17]
We have a function in the package 'getConceptSetsAndConceptsFromCohort'. This function gets both concept-set expression and individual concepts from cohort. It takes a significant amount of time to resolve every concept set expression.

Most of the time, we only need the concept-set expression in the cohort definition. So a function that only provides concept set expression would be useful.

**Comment by schuemie** [comment]
Maybe instead of creating many different functions, we could create a single function `getConceptSetsFromCohort` that has arguments specifying what exactly you want to get? E.g.

```r
getConceptSetsFromCohort(baseUrl = "http://my_url", 
                         cohortDefinitionId = 1, 
                         getExpression = TRUE, 
                         getIncludedConcepts = FALSE)
```

**Comment by gowthamrao** [comment]
I like this idea

**Comment by alondhe** [comment]
Yes, and this function name rolls of the tongue way better 😃

**Comment by gowthamrao** [comment]
Maybe we should refactor this package in a development branch to have one function per major Atlas function

e.g. Cohort, Characterization, Incident Rate etc.

**Comment by schuemie** [comment]
I think this function is no longer needed. Using the new pattern, you would just [`getCohortDefinition`](https://github.com/OHDSI/ROhdsiWebApi/blob/develop/R/CohortDefinition.R#L37) and inspect the resulting R object to get the concept sets. You could resolve them using [`resolveConceptSet`](https://github.com/OHDSI/ROhdsiWebApi/blob/develop/R/ConceptSet.R#L71).
