### ISSUE TITLE
Connecting to a webAPI thougth https 

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [OHDSI/ROhdsiWebApi#175]
Our webAPI is serverd has changed from http to https and ROhdsiWebApi stopped working. 

I can set a certificate for the httr;; package but functions keep failing at this point 

https://github.com/OHDSI/ROhdsiWebApi/blob/23eaf1e0fe3f7f6a4aae6dcfb3ebdb8fd39ed900/R/Private.R#L22

with error "status was SSL peer certificated or SSH remote was not OK". 

Is there a solution to this?
Should `.isValidUrl` test the url validity using httr:: functions to fix this issue ??

**Comment by ChenyuL** [comment]
Hi all, I have a similar issue:  
It seems I can not get the correct authorization for using the WebApi. So I'm not able to use the getDefinitionsMetadata function. 
![image](https://user-images.githubusercontent.com/17032366/111661783-b80c3380-87e5-11eb-8757-56eec72671f8.png)

**Comment by gowthamrao** [comment]
Hi @ChenyuL @javier-gracia-tabuenca-tuni Can you please try the develop version of ROhdsiWebApi. We have added security support and would love feedback from you.
