### ISSUE TITLE
Can we add tests for security

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/ROhdsiWebApi#176]
@ablack3

**Comment by gowthamrao** [comment]
@azimov

The manual test code here seems to be failing https://github.com/OHDSI/ROhdsiWebApi/blob/develop/extras/TestCode.R

**Comment by gowthamrao** [comment]
@schuemie how do we perform tests :)

We need to port the manual test code above to test_that here https://github.com/OHDSI/ROhdsiWebApi/blob/develop/tests/testthat/test-webapi.R

We then need a version with and without security enabled. 


```

Error in .request(url, method = "PUT", config = config, handle = handle,  : 
  Bad Request (HTTP 400).
```

**Comment by gowthamrao** [comment]
@leeevans we need two webapi test environments for ROhdsiWebAPi.
- an unsecured webapi service
- a few types of secured webapi service

The purpose is to test ROhdsiWebApi and potentially to use it for new development, vignettes, demo, training etc (if needed).

May we discuss?

**Comment by gowthamrao** [comment]
@azimov did you get a chance to replicate the manual tests and the error i found
```

Error in .request(url, method = "PUT", config = config, handle = handle,  : 
  Bad Request (HTTP 400).
```

Once manual tests are done - we can begin porting them to the automated tests

**Comment by gowthamrao** [comment]
This has now been partially implemented. More to come in 1.3

**Comment by gowthamrao** [comment]
Version 1.2 is now released. Current testing framework relies on a live webapi instance. We attempted to use the public atlas instance - and found it to be not reliable for test purpose. So we decided to disable it. It reduces the test coverage to < 10% from > 50%.

To get the real test coverage, we would need a 'dedicated' test environment to support increasing test coverage. we discussed a plumber based solution (modeling after what @ablack3 worked on). This is expected to take time - and we decided to move it to next release. 

@leeevans please let us know if you have begun working on it, but this is targeted for a future release.

**Comment by azimov** [comment]
On this topic, the tests now support instances of atlas that implement AD/LDAP, database and windows authentication set with environment variables as we should support these instances of webapi. This has been tested locally so it should be as strightforward as adding the options to the github actions configuration (and then fixing any broken tests).
