### ISSUE TITLE
Remove trailing backslash from base URL

### ISSUE THREAD

**Issue by ablack3** [OHDSI/ROhdsiWebApi#187]
Many ROhdsiWebApi functions take a base URL. If the base URL includes a trailing backslash then the api call will fail. 

``` r
library(ROhdsiWebApi)
getWebApiVersion("https://atlas.ohdsi.org/WebAPI")
#> [1] "2.8.1"
getWebApiVersion("https://atlas.ohdsi.org/WebAPI/")
#> Error in getWebApiVersion("https://atlas.ohdsi.org/WebAPI/"): Please check if the url is valid. https://atlas.ohdsi.org/WebAPI/ . Failed while retrieving WebApi information.
```

<sup>Created on 2021-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Should ROhdsiWebApi automatically remove any trailing backshashes from a baseURL argument?

I think this would be not be difficult to implement but would require changes to every function that accepts a baseUrl which is a lot.

Are there any potential issues caused by removing trailing slashes from URLs?

**Comment by gowthamrao** [comment]
@azimov did you get to this yet :)

**Comment by azimov** [comment]
@gowthamrao  see #191
