### ISSUE TITLE
Atlas cohort Id are referred interchangeably as definitionId and cohortId

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/ROhdsiWebApi#21]
Use cohortId instead of definitionId in a consistent manner to identify atlas cohort definition id

**Comment by vojtechhuser** [comment]
+1

**Comment by gowthamrao** [comment]
@schuemie and @gowthamrao  discussed. This would be an important breaking change. We will use consistent name to identify identifiers in WebApi. Since ROhdsiWebApi lifecycle is early (no version number) - we feel it is reasonable to introduce breaking changes. This change is important to ensure it does not cause larger pain in the future - as reliance on this package/number of users increase.

Note: We explored the use of alias in R - but it is more likely to cause confusion and errors.

**Comment by gowthamrao** [comment]
@schuemie unless you disagree, i propose we use 'id' to uniquely identify any WebApi 'id', and then use category (where appropriate) to categorize the id type.

As used in this generic function https://github.com/OHDSI/ROhdsiWebApi/blob/c749008354ae43250bdb22bc03f1cbc4e9d52a1e/R/WebApi.R#L176
