### ISSUE TITLE
Variable names should be camelCase

### ISSUE THREAD

**Issue by schuemie** [OHDSI/ROhdsiWebApi#22]
Ad defined in the [OHDSI R style guide](https://www.ohdsi.org/web/wiki/doku.php?id=development:ohdsi_code_style_for_r), variable names should use camelCase. Currently, functions like `getConceptSetsAndConceptsFromCohort` return snake_case names instead.

One solution could be to use the [snakeCaseToCamelCase](https://github.com/OHDSI/SqlRender/blob/master/R/HelperFunctions.R#L209) function in SqlRender.

**Comment by gowthamrao** [comment]
Are there any other functions that are not following this style?
