### ISSUE TITLE
WebAPI pulse check page

### ISSUE THREAD

**Issue by alondhe** [OHDSI/ROhdsiWebApi#228]
Hi all,

Just thinking "aloud" here, but I'm wondering if having a Shiny app that can be deployed by Atlas site admins and IT support teams in which the pulse of WebAPI can be checked would be a useful addition to quicker troubleshooting.

Thinking of showing:
1. WebAPI is up (hit the info endpoint)
2. SOLR is up (if configured)
3. CDM, vocab, and CEM hosts are available (use the check connection endpoint)
4. security is enabled and working (related to #178)

Thoughts?

Ajit

**Comment by gowthamrao** [comment]
Agree. @alondhe would that do?
