### ISSUE TITLE
getCohortGenerationStatuses issue with definitionIds vector element length

### ISSUE THREAD

**Issue by jamieweaver** [OHDSI/ROhdsiWebApi#23]
this line (https://github.com/OHDSI/ROhdsiWebApi/blob/master/R/CohortDefinition.R#L391) fails when the definitionIds argument is passed a vector where the numeric elements are not all the same length. 

e.g.
definitionIds <- c(10593, 10599, 11894, 10608, 11643, 10607, **2538**, 1060)

ROhdsiWebApi::getCohortGenerationStatuses(baseUrl = baseUrl,
                                                           sourceKeys = c("CPRD", "IBM_CCAE"),
                                                           definitionIds = definitionIds)

**Comment by alondhe** [comment]
@jamieweaver -- can you try again using the develop branch?

`devtools::install_github("OHDSI/ROhdsiWebApi", ref = "develop")`

**Comment by gowthamrao** [comment]
@jamieweaver  have you tested this on branch?

**Comment by gowthamrao** [comment]
Addressed through https://github.com/OHDSI/ROhdsiWebApi/pull/95/commits/c47dc93a15ff9e2de66de49484a5e0078a5b3937 https://github.com/OHDSI/ROhdsiWebApi/pull/95
