### ISSUE TITLE
Authentication using SAML

### ISSUE THREAD

**Issue by nadavrap** [OHDSI/ROhdsiWebApi#256]
Hi,
In the `ROhdsiWebApi::authorizeWebApi` function, there are three authentication methods, but none of those are SAML. Is there an option to authenticate using SAML?

**Comment by gowthamrao** [comment]
Also here https://forums.ohdsi.org/t/is-it-possible-to-authenticate-using-rohdsiwebapi-with-saml/18029/2

> 
> if you have signed in to webapi (i.e. atlas login) using ur SAML, then i think ROhdsiWebApi can use “ad” as described [here](https://ohdsi.github.io/ROhdsiWebApi/reference/authorizeWebApi.html)
> 
> Full info is [Using ROhdsiWebApi with security enabled Atlas/WebAPI • ROhdsiWebApi](https://ohdsi.github.io/ROhdsiWebApi/articles/authenticationSecurity.html)
> 
> Please give it a try - if not please post an issue or contribute code

**Comment by nadavrap** [comment]
Apparently, what I was facing is SAML but based on Google. So the steps described [here](https://ohdsi.github.io/ROhdsiWebApi/articles/authenticationSecurity.html#google-authentication)  worked.
Thank you @gowthamrao
