### ISSUE TITLE
Change checkBaseUrl to simply /info web service call

### ISSUE THREAD

**Issue by alondhe** [OHDSI/ROhdsiWebApi#33]
Rather than challenging the baseUrl by checking the format of it, perhaps we instead just call the /info web service of the WebAPI baseUrl to ensure we get a version back. This ensures we don't need to assume the URL conventions used by any site.

**Comment by gowthamrao** [comment]
Could we please check if there is a trailing '/' or when we generate the url by pasting segments - it does not lead to '//'

as discussed here https://github.com/OHDSI/ROhdsiWebApi/issues/60#issuecomment-620540472

**Comment by gowthamrao** [comment]
@schuemie  @alondhe  is this issue resolved?

**Comment by gowthamrao** [comment]
I think this is resolved. Closing this issue @alondhe  @schuemie  please reopen if you think otherwise
