### ISSUE TITLE
Use readr to read and write CSV files

### ISSUE THREAD

**Issue by schuemie** [OHDSI/ROhdsiWebApi#43]
This should prevent problems with trailing spaces in file names, as noted [here](https://github.com/OHDSI/CohortDiagnostics/issues/39#issuecomment-613944951).

Specifically, we should change this [here](https://github.com/OHDSI/ROhdsiWebApi/blob/develop/R/CohortDefinition.R#L188),

**Comment by gowthamrao** [comment]
Also relates to https://github.com/OHDSI/WebAPI/issues/1510
