### ISSUE TITLE
Add News.md

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/ROhdsiWebApi#47]
http://r-pkgs.had.co.nz/release.html

https://github.com/OHDSI/ROhdsiWebApi/issues/36#issuecomment-615282830

**Comment by schuemie** [comment]
The NEWS.md file should be updated as part of the [release process]( https://ohdsi.github.io/MethodsLibrary/releaseProcess.html).

See for example [the ParallelLogger NEWS file](https://github.com/OHDSI/ParallelLogger/blob/master/NEWS.md).

**Comment by gowthamrao** [comment]
Is news.md manually generated or using a script in say PackageMaintenance.R?

I also like how @anthonysena  manages these https://github.com/OHDSI/WebAPI/releases

**Comment by schuemie** [comment]
The NEWS.md file must be manually created. We don't necessarily have a 1-on-1 relationship between the things in the NEWS file and issues. The NEWS file is to inform users of the package on what has changed.
