### ISSUE TITLE
Sprint to v0.1.0?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/ROhdsiWebApi#52]
@alondhe , @gowthamrao , there are some important changes in develop that people would likely need (actually, Ajit's change in the checkUrl is the most important one). I'd like to propose we work towards a release.

I've created a straw-man [milestone](https://github.com/OHDSI/ROhdsiWebApi/milestone/1) of things I think can be achieved in the short term, and should make for a consistent release. Let me know what you think.

**Comment by gowthamrao** [comment]
Should we target a release date and block some time to collaborate on this?

**Comment by schuemie** [comment]
Yes, sounds good. Should we target 2 weeks from now (May 11)?

@gowthamrao : just curious: why did you add 'Sprint v0.1.0' labels to all tasks that were already 'labeled' as being being part of the 'v0.1.0' milestone?

**Comment by gowthamrao** [comment]
@schuemie because i did not see milestone and was github illiterature. The label is redundant (i missed the milestone)

**Comment by gowthamrao** [comment]
Closing in favor of https://github.com/OHDSI/ROhdsiWebApi/issues/93
