### ISSUE TITLE
Get and Set CohortDefinitions

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/ROhdsiWebApi#60]
Not sure this is already in a Roadmap but a handy feature would be if i could export a list of cohortDefinitions from public Atlas and import them in my own Atlas.

To do this now I am exporting them in Atlas or I can use the functionality that Martijn made earlier that we use to make study packages, but importing is a manual step.

If this functionality is already available in someway in the code base please let me know.

Thanks

**Comment by gowthamrao** [comment]
Hi @PRijnbeek - Yes, it already exists, but not fully tested - so you could help us! We worked on it recently. 

To achieve your goal, you can follow these steps:
1. Get the list of atlas definitions from the source atlas webapi into a dataframe using this function: `getAtlasDefinitionsDetails` https://github.com/OHDSI/ROhdsiWebApi/issues/40 Then filter them locally in R to select the cohort definitions that you would like to extract expressions for. This will give you a list of cohortIds - you can obviously skip this step if you already have the list cohortIds.
1. For each of the cohortIds get the cohort definition expressions from source atlas-webapi using this function `getCohortDefinition`. Note these will be R-objects (not JSON) as described here in our [generic design pattern](https://github.com/OHDSI/ROhdsiWebApi/issues/37). You will have to convert it into JSON as in this [example](https://github.com/OHDSI/ROhdsiWebApi/blob/d42b17a614af20ea25dba21fb87118cd0913c27a/R/WebApi.R#L264).
4. You can then post them to your target atlas-webapi using `postAtlasDefinition` [here](https://github.com/OHDSI/ROhdsiWebApi/issues/42). Note: `postAtlasDefinition` has not been merged yet.

i made these contributions based on the experience in our Covid collaboration - where we were copying definitions from one atlas instance to another. Using this approach, we can achieve this using a script and also introduce error management/quality controls. A enhancement would be to also compare JSON expressions to ensure we are not duplicating cohort definitions or accidentally making changes (to do).

**Comment by vojtechhuser** [comment]
+1 on this problem

**Comment by PRijnbeek** [comment]
If I do this I get the json:

cohortId <- 1773955
baseUrl <- "http://api.ohdsi.org/WebAPI/"
url <- paste0(baseUrl, "cohortdefinition/", cohortId)
json <- httr::GET(url)
json <- httr::content(json)

If I do this I get a 404.
cohortId <- 1773955
baseUrl <- "http://api.ohdsi.org/WebAPI/"
validJsonExpression <- getCohortDefinition(baseUrl = baseUrl, cohortId = cohortId)

Why is that?

**Comment by gowthamrao** [comment]
Hi @PRijnbeek , i think that is a design decision. Based on discussion with @schuemie here https://github.com/OHDSI/ROhdsiWebApi/issues/37 and [here](https://github.com/OHDSI/ROhdsiWebApi/pull/32#issuecomment-603618970) a decision was made that functions would return objects that are objects that maybe inspected in R (such as dataframe) vs. Json. 

Based on this, `getCohortDefinition` converts the json to data [here](https://github.com/OHDSI/ROhdsiWebApi/blob/8cbc2b88a858fd705dcb415642f5f8a2b4e2ea34/R/CohortDefinition.R#L46) 

You can convert it back to JSON as shown [here](https://github.com/OHDSI/ROhdsiWebApi/blob/d42b17a614af20ea25dba21fb87118cd0913c27a/R/WebApi.R#L264)

**Comment by schuemie** [comment]
@gowthamrao : How does that explain that the function throws a 404 error when the cohort exists in the WebAPI?

**Comment by gowthamrao** [comment]
Aah - i totally misread @PRijnbeek  question. Let me look into it

**Comment by gowthamrao** [comment]
The answer is simple
the baseUrl has to be in the form "http://server.org:80/WebAPI"

@PRijnbeek  has "http://api.ohdsi.org/WebAPI/"  i.e. it ends with a slash '/'.

This is causing the url to be "http://api.ohdsi.org/WebAPI//cohortdefinition/1773955" 

Causing the 404 error.

@schuemie  do we need to introduce error handler in checkBaseUrl?

**Comment by PRijnbeek** [comment]
Okay thanks, showing the full path would have been helpful in the error message. I think it makes mor sense to not have the slash at the end indeed.

**Comment by schuemie** [comment]
Whether or not the user provides a slash at the end should not matter. We need to add some code to check if it's there, and remove it if it is.

The code in the develop branch would have given a more informative error message (or maybe actually would have just worked). We had better get working on that release ;-)

**Comment by gowthamrao** [comment]
Sounds like we need to get this done https://github.com/OHDSI/ROhdsiWebApi/issues/52

**Comment by PRijnbeek** [comment]
I am actually using the develop branch (was not aware i should not) and had this issue

**Comment by schuemie** [comment]
Hmmm, that is weird. We'll look into it

**Comment by gowthamrao** [comment]
In master we regular expression for .[checkBaseUrl ]
https://github.com/OHDSI/ROhdsiWebApi/blob/8ed2756f727753d3d031405b633c993369c5eb18/R/WebApi.R#L20

In develop we have
https://github.com/OHDSI/ROhdsiWebApi/blob/8cbc2b88a858fd705dcb415642f5f8a2b4e2ea34/R/WebApi.R#L20

Is this the reason?

**Comment by cgreich** [comment]
Friends: I am not following. Atlantes are rarely public. In fact, the only ones public are the one on ohdsi.org, and the ones we pull up for the Tutorials. IQVIA also has one on the public internet. But other than that - didn't we want to have Arachne be the entity that would direct traffic in and out of a protected institution? Allowing for security and governance? 

Obviously, cohort definitions are harmless, but everything else in Atlas is highly protected.

**Comment by gowthamrao** [comment]
>  Atlantes are rarely public. In fact, the only ones public are the one on ohdsi.org, and the ones we pull up for the Tutorials.

@cgreich i dont know about Arachne, but from design standpoint - we need to ensure that the content being securely transferred is auditable and never a blackbox. The content being transferred should be in 'text' format - and can be audited by simple tools like notepad. Putting gates in the transfer process gives more control from security standpoint.

This design, using ROhdsiWebApi achieves these design principles. Each of these are seperate steps - with gates in between.

1. [Institution 1 firewall] - pull data from atlas into text - human readable (json expression). This may be audited. 
1. [securely transfer to institution 2] - text - human readable is transferred. ROhdsiWebApi does not FTP a file. It only works within a firewall. So the text files have to be transferred securely between institutions using some other mechanism (gate).
1. [Institution 2 firewall] - read the text data into R and then use ROhdsiWebApi post data  into atlas

Transfer between Atlantes on different networks are not handled by ROhdsiWebApi. i.e. the text files have to be securely transferred between fire-walled network using alternate methods
