### ISSUE TITLE
Import/export of cohorts acros servers

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/ROhdsiWebApi#61]
Good document/guidance on showing what package to use (OhdsiSharing) or ROhdsiWebApi  (vs. (also LEGENDS R code for that)

Can cohort.csv also include URL of the server to import from?

E.g., my cohorts are on multiple servers.
e.g., some are on covid-atlas others on atlas-demo server or final atlas server. How to juggle all this

@msuchard @anthonysena

**Comment by vojtechhuser** [comment]
And same for even characterization study. Even if one server does not allow import, even just good export of various .json artifacts into set of files would be good to have overview about.

**Comment by gowthamrao** [comment]
@vojtechhuser  similar/same question here 
https://github.com/OHDSI/ROhdsiWebApi/issues/60

Could we move to that thread?

**Comment by cgreich** [comment]
Guys: Why is this not Arachne? Are we reinventing wheels?

**Comment by schuemie** [comment]
Arachne is a promising idea, but currently not many people are running it. I've posted [suggestions on how to change that ](https://forums.ohdsi.org/t/steering-committee-proposal-to-standardize-network-studies/7846/4?u=schuemie) in the past. 

And regardless, it would be good to have a solution that works from R. @cgreich , I know you don't like R, but for many people in the OHDSI community R is their main analytics platform.

**Comment by gowthamrao** [comment]
Could we please move the conversation to here https://github.com/OHDSI/ROhdsiWebApi/issues/60
Closing this thread.
