### ISSUE TITLE
get templated SQL from webApi for a json expression

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/ROhdsiWebApi#97]
It would be useful if WebApi is able to return templated OHDSI SQL for a given JSON expression. E.g. for a cohort JSON expression, obtained templated cohort SQL.

@chrisknoll 
Would this be possible? Would it be possible for cohort, cohort generation, pathway, incidence rate?

Currently it is possible to get cohort SQL given a cohortId.

**Comment by chrisknoll** [comment]
This endpiont will take a POST of a json `GenerateSqlRequset` and return the SQL:

https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java#L340

**Comment by gowthamrao** [comment]
@chrisknoll Thanks!! are there end-points for Incidence rate/pathways too?

**Comment by chrisknoll** [comment]
No, those queries are a bit more complicated such that they write to multiple results tables, etc...the cohort definition query is handled in a way that you can get a raw query to populate the target table, but those other more complicated queries are writing to multiple tables.  At the time, it seemed to be more risky vs. reward for exposing those, but it is possible to just expose the analysis SQL  that is executed in the background tasklets.

**Comment by gowthamrao** [comment]
Would it be possible to expose those in WebApi so that we may get the analysis SQL? i.e. given the JSON expression of incidence rate, cohort pathways, or characterization - get their analysis SQL template? 

What i am hoping is that we can then render the templated SQL using SqlRender in R. We are able to do this with R - and CohortDiagnostics package use this capability of getting SQL from cohort JSON expression. But we cant do them for other SQL based categories like Incidence, pathway and characterization.

**Comment by gowthamrao** [comment]
Also https://github.com/OHDSI/ROhdsiWebApi/pull/125

Only able to support sql for cohorts at this time
